HD_COMPONENT_NAME	= ftools

HD_COMPONENT_VERS	= 

HD_CTASK		= fverify

HD_CTASK_SRC_c		= hfverify.c fverify.c fvrf_data.c fvrf_file.c \
			  fvrf_head.c fvrf_key.c fvrf_misc.c

HD_CFLAGS		= ${HD_STD_CFLAGS}

HD_CLIBS		= ${HD_STD_CLIBS} ${F77LIBS4C}

HD_INSTALL_TASKS	= ${HD_CTASK}

HD_INSTALL_PFILES	= fverify.par

HD_INSTALL_HELP		= fverify.hlp fverify.txt

include ${HD_STD_MAKEFILE}
